Fix: allow 0x prefix when passing hex-encoded parameters
aurora-is-near/aurora-cli-rs pull request #7
Opened 2023-03-07 19:52 UTC by birchmd

The `hex` crate and `Address::decode` functions do not expect an `0x` prefix on hex-encoded data. However it is standard to include such a prefix for most blockchain RPCs / explorers. For ease of use, it make sense for the CLI to accept an `0x` prefix too.

This PR adds some new functions to the `utils` module that can parse hex-encoded data with an `0x` prefix and then uses those new functions throughout the code.

2023-03-08 06:58 UTC, aleksuss commented
@birchmd  I already did almost the same changes in my working branch but did not push yet 😄

2023-03-08 07:00 UTC, aleksuss approved these changes

2023-03-08 08:28 UTC, aleksuss commented on src/utils.rs
> +pub fn hex_to_arr<const N: usize>(h: &str) -> Result<[u8; N], hex::FromHexError> {
👍🏻

2023-03-08 10:23 UTC, hskang9 requested changes
I would approve after removing `unwrap()` thanks to using this utils method.

2023-03-08 10:23 UTC, hskang9 commented on src/cli/aurora.rs
> +                let tx_hash = aurora_engine_types::H256(utils::hex_to_arr(&tx_hash_hex).unwrap());
Now that we use `hex_to_arr` functions, it seems we can remove `unwrap()` with `?`. @birchmd can you remove unwrap as error handling PR is proceeding? https://github.com/aurora-is-near/aurora-cli-rs/pull/6.

2023-03-08 10:23 UTC, hskang9 commented on src/cli/aurora.rs
> +                let tx_hash = aurora_engine_types::H256(utils::hex_to_arr(&tx_hash_hex).unwrap());
`aurora_engine_types::H256(utils::hex_to_arr(&tx_hash_hex)?);`

2023-03-08 10:48 UTC, hskang9 commented on src/cli/aurora.rs
> +                let tx_hash = aurora_engine_types::H256(utils::hex_to_arr(&tx_hash_hex).unwrap());
Ok, so I guess we are in development stage? I was asked to put down request for changes, and I will do that in PR #6

2023-03-08 10:49 UTC, hskang9 approved these changes

2023-03-08 10:54 UTC, merged

2023-11-06 21:09 UTC, mrLSD approved these changes